### ISSUE TITLE
reader: set max number of lines to read in each CSV file

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/watchman#18]
Right now `Reader` calls `ReadAll()` (from `encoding/csv.Reader`), but there's a [proposed change to switch to `Read()`](https://github.com/adamdecaf/ofac/commit/f7e92a0f27513e9463f5311909566fa9546cc435). Either way we should ideally cap the max bytes/lines read so we don't DOS ourselves.

**Comment by bkmoovio** [comment]
Changed this to a question.  Having Slack discussions with Adam as to whether using ReadAll() will be an issue.  reading all records into memory.

ReadAll reads all the remaining records from r.
// Each record is a slice of fields.
// A successful call returns err == nil, not err == io.EOF. Because ReadAll is
// defined to read until EOF, it does not treat end of file as an error to be
// reported.
