### ISSUE TITLE
Change minimum threshold from .99 to .95

### ISSUE THREAD

**Issue by wadearnold** [moov-io/watchman#319]
We should change the default blocking amount from .99 to .95. At .99 you have to have an almost exact match for it to block. 

https://github.com/moov-io/watchman/blob/0e56292db1aa6484ce7d23bea6ac2f38cec02c83/cmd/batchsearch/main.go#L51****

**Comment by adamdecaf** [comment]
We can change the default recommended in our documentation, but it's always left up to the caller to determine what `match: 0.981512` means to their application. That `batchsearch` is mostly used for testing and offers a CLI for checking a text file - I don't know anyone who uses it. 

We recommended 0.99 because it's worked for our US-based names. In other regions that default (and precomputation steps) will need adjusted. That support is lacking currently.

**Comment by adamdecaf** [comment]
https://github.com/moov-io/watchman/issues/330 might be a better option for this. The search results returned are not "positive matches." They're the top N results. Adding a query parameter to return results only above a certain percentage would put us more in line with the OFAC sanctions search engine.

**Comment by adamdecaf** [comment]
With https://github.com/moov-io/watchman/issues/330 we have `?minMatch=0.90` that folks can use to accomplish this.
